import "server-only";
import { drizzle as drizzlePg } from "drizzle-orm/node-postgres";
import { drizzle as drizzlePglite } from "drizzle-orm/pglite";
import * as schema from "./schema";

// ---------------------------------------------------------------------------
// One database entry point for both environments:
//
//   Production (Vercel):  DATABASE_URL points at Neon Postgres — provisioned
//                         through the Vercel Marketplace, env pulled with
//                         `vercel env pull`.
//   Local development:    no DATABASE_URL → PGlite, a real in-process
//                         Postgres that stores its data in .data/pglite.
//                         Same SQL dialect, same schema, zero setup.
//
// Schema migrations (from ./drizzle, generated by `npm run db:generate`)
// are applied automatically on first use — idempotent and cheap, so no
// manual migrate step is ever needed locally or on deploy.
// ---------------------------------------------------------------------------

type Db = ReturnType<typeof drizzlePg<typeof schema>>;

declare global {
  // Survives dev-server hot reloads so we don't reconnect/remigrate.
  var __tfmDb: Promise<Db> | undefined;
}

async function createDb(): Promise<Db> {
  const url = process.env.DATABASE_URL;
  if (url) {
    const { Pool } = await import("pg");
    const { migrate } = await import("drizzle-orm/node-postgres/migrator");
    const pool = new Pool({ connectionString: url, max: 5 });
    const db = drizzlePg(pool, { schema });
    await migrate(db, { migrationsFolder: "./drizzle" });
    return db;
  }

  const { PGlite } = await import("@electric-sql/pglite");
  const { migrate } = await import("drizzle-orm/pglite/migrator");
  const path = await import("node:path");
  const { mkdir } = await import("node:fs/promises");
  const dir = path.join(process.cwd(), ".data", "pglite");
  await mkdir(dir, { recursive: true });
  const client = new PGlite(dir);
  const db = drizzlePglite(client, { schema });
  await migrate(db, { migrationsFolder: "./drizzle" });
  // The two drizzle flavors expose an identical query API for our usage.
  return db as unknown as Db;
}

export function getDb(): Promise<Db> {
  if (!globalThis.__tfmDb) globalThis.__tfmDb = createDb();
  return globalThis.__tfmDb;
}

export * from "./schema";
